### ISSUE TITLE
Add to made in Iran repo

### ISSUE THREAD

**Issue by ghost** [sina-yeganeh/kid-keeper#1]
Hi,sina.I added your project in my," made in iran" projects list 
[https://github.com/hasan-kashi/made-in-iran](https://github.com/hasan-kashi/made-in-iran)

Good luck!

**Comment by sina-yeganeh** [comment]
Hi! Thank for this 😉
I Think you should add "*Command Line*" Project or "*Command Line Tool*" in
your README.md.
Bye!👊
